Egien Vector and Eigen value

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

A is squrae matrix
$[1, 0 ],
[0 ,-2]$
v-->eigenvector
lambda ---> eigenvalue
la.eig will return a tuple (eigvals, eigvecs)

A*v = lambda*v
Bleow code proves the same

In [4]:
A = np.array([[1,0],[0,-2]])  # Initialize an symmertix array
eigvals, eigvecs = la.eig(A) #get the eigen values and vetors
print('eigvals:', eigvals)
print('eigvecs:', eigvecs)
eigvals = eigvals.real # eigen values are not complex as A is symmetric matrix
print('eigvals are real for symmetric matrix:',eigvals)
lambda1 = eigvals[1] 
#print("lamda1 :", lambda1)
v1 = eigvecs[:,1].reshape(2,1)
#A @ v1 = lambda1 * v1

print( A@v1 == lambda1*v1) # hence proved A*v = lambda*v

eigvals: [ 1.+0.j -2.+0.j]
eigvecs: [[1. 0.]
 [0. 1.]]
eigvals are real for symmetric matrix: [ 1. -2.]
[[ True]
 [ True]]


In [19]:
v1 = eigvecs[:,1]
v1.reshape(2,1)
v1


array([0., 1.])

In [27]:
A @ v0

array([1., 0.])

In [38]:
lambda0 = eigvals[0]

In [40]:
lambda0 * v0

array([1., 0.])

In [22]:
v0 = eigvecs[0,:]
v0.reshape(2,1)
v0

array([1., 0.])