Symmetric Matrices

The eigenvalues of a symmetric matrix are always real and the eigenvectors are always orthogonal! 

Below example will prove the same

In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
#lets generate a 4X4 matrix
n=4
P = np.random.randint(0,10,(n,n))
P

array([[5, 6, 1, 8],
       [6, 8, 9, 2],
       [8, 4, 2, 4],
       [7, 3, 4, 5]])

In [3]:
#Take the transpose of P
P.T

array([[5, 6, 8, 7],
       [6, 8, 4, 3],
       [1, 9, 2, 4],
       [8, 2, 4, 5]])

In [5]:
# matix multiplication of matix and its tranpose always give a symmetric matrix

S = P @ P.T
print(S)

[[126 103  98  97]
 [103 185 106 112]
 [ 98 106 100  96]
 [ 97 112  96  99]]


In [6]:
#get the eigenvalues and eigenvector of Symmetrix matrix S
eigvals, eigvecs = la.eig(S)
print(eigvals)  #as S is symmetric eigenvals are real
print(eigvecs)

[438.21143511+0.j  53.58882853+0.j  15.07315854+0.j   3.12657782+0.j]
[[-0.48100388 -0.58161483  0.65593156 -0.01064159]
 [-0.59032595  0.76511209  0.24422567 -0.08045235]
 [-0.45533641 -0.24139194 -0.55849214 -0.64998863]
 [-0.46132342 -0.1343786  -0.44519001  0.75559841]]


In [7]:
#Check - eigen vector are orthogonal

v0 = eigvecs[:,0]
v1 = eigvecs[:,1]
v2 = eigvecs[:,2]
v3 = eigvecs[:,3]

In [8]:
round(v0 @ v1,2)  # for orthogonal it should be zero

0.0